/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MrCard {
    }
    interface MrLittleButton {
        "anchor": boolean;
    }
    interface MrProfilButton {
    }
    interface MrTooltip {
        "position": string;
        "shortcut": string;
        "text": string;
    }
}
declare global {
    interface HTMLMrCardElement extends Components.MrCard, HTMLStencilElement {
    }
    var HTMLMrCardElement: {
        prototype: HTMLMrCardElement;
        new (): HTMLMrCardElement;
    };
    interface HTMLMrLittleButtonElement extends Components.MrLittleButton, HTMLStencilElement {
    }
    var HTMLMrLittleButtonElement: {
        prototype: HTMLMrLittleButtonElement;
        new (): HTMLMrLittleButtonElement;
    };
    interface HTMLMrProfilButtonElement extends Components.MrProfilButton, HTMLStencilElement {
    }
    var HTMLMrProfilButtonElement: {
        prototype: HTMLMrProfilButtonElement;
        new (): HTMLMrProfilButtonElement;
    };
    interface HTMLMrTooltipElement extends Components.MrTooltip, HTMLStencilElement {
    }
    var HTMLMrTooltipElement: {
        prototype: HTMLMrTooltipElement;
        new (): HTMLMrTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "mr-card": HTMLMrCardElement;
        "mr-little-button": HTMLMrLittleButtonElement;
        "mr-profil-button": HTMLMrProfilButtonElement;
        "mr-tooltip": HTMLMrTooltipElement;
    }
}
declare namespace LocalJSX {
    interface MrCard {
    }
    interface MrLittleButton {
        "anchor"?: boolean;
    }
    interface MrProfilButton {
        "onButtonToggle"?: (event: CustomEvent<any>) => void;
    }
    interface MrTooltip {
        "position"?: string;
        "shortcut"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "mr-card": MrCard;
        "mr-little-button": MrLittleButton;
        "mr-profil-button": MrProfilButton;
        "mr-tooltip": MrTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mr-card": LocalJSX.MrCard & JSXBase.HTMLAttributes<HTMLMrCardElement>;
            "mr-little-button": LocalJSX.MrLittleButton & JSXBase.HTMLAttributes<HTMLMrLittleButtonElement>;
            "mr-profil-button": LocalJSX.MrProfilButton & JSXBase.HTMLAttributes<HTMLMrProfilButtonElement>;
            "mr-tooltip": LocalJSX.MrTooltip & JSXBase.HTMLAttributes<HTMLMrTooltipElement>;
        }
    }
}
